### ISSUE TITLE
AttributeError: module 'PYEVALB.scorer' has no attribute 'evalb'

### ISSUE THREAD

**Issue by asmundur** [flyaway1217/PYEVALB#2]

**Comment by flyaway1217** [comment]
Can you provide the code when you used PYEVALB?

**Comment by asmundur** [comment]
I'm just trying to run your minimal sample code, nothing more or less than that. My python version is 3.6.7

**Comment by flyaway1217** [comment]
I ran for a few tests. It failed in both python 3.6.0 and 3.6.7.
I suspect that this might have something to do with the import directory.
I do not have time for debugging now.
I will try to fix this by the end of this week.

**Comment by asmundur** [comment]
this happens also in python 3.5.2

**Comment by flyaway1217** [comment]
I looked into the code carefully and did not find any bugs.
The problem is the examples. I have updated the readme file.
Now, these example codes should be runnable.
